baseURL: https://joganacontadainfra.com.br
languageCode: pt-br
theme: hugo-theme-stack
pagination:
    pagerSize: 5
title: Î» JogaNaContaDaInfra

# Change it to your Disqus shortname before using
disqusShortname: thiagoborba-me

# GA4 Tracking ID (upgraded from Universal Analytics)
googleAnalytics: G-XXXXXXXXXX

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl
defaultContentLanguage: pt-br   

# Build configuration
timeout: 60000
build:
  writeStats: true
  useResourceCacheWhen: fallback

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: code

    footer:
        since: 2017
        customText:

    dateFormat:
        published: 02/Jan/2006
        lastUpdated: 02/Jan/2006

    sidebar:
        emoji: ðŸ“Ž
        subtitle: "\"Porque quem nunca quebrou a infra que atire o primeiro log!\""
        avatar:
            local: true
            src: img/arq5avatar.jpg

    article:
        math: true
        toc: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - name
                - email
                - url
            placeholder:
            locale:
                admin: Admin

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site: thiagoborbame

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
            icon: home

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100
        - name: categories
          weight: 200

# Modern Hugo features
minify:
    disableXML: true
    minifyOutput: true
    tdewolff:
        css:
            keepCSS2: true
        html:
            keepConditionalComments: true
            keepDefaultAttrVals: true
            keepDocumentTags: true
            keepEndTags: true
            keepQuotes: true
            keepWhitespace: false
        js:
            keepVarNames: true
            version: 2022
        json:
            keepNumbers: true
        svg:
            keepComments: true
        xml:
            keepWhitespace: false

# Performance optimizations
imaging:
    resampleFilter: Lanczos
    quality: 75
    anchor: Smart

# Security headers
security:
    func:
        getenv:
            - ^HUGO_
        toCSS:
            - ^https?://
        toJS:
            - ^https?://

# Output formats
outputs:
    home:
        - HTML
        - RSS
    page:
        - HTML
    section:
        - HTML
        - RSS

# Taxonomies
taxonomies:
    category: categories
    tag: tags
    series: series

# Caching
caches:
    assets:
        dir: :resourceDir/_gen
        maxAge: -1
    images:
        dir: :resourceDir/_gen/images
        maxAge: -1
    getjson:
        dir: :cacheDir
        maxAge: -1
    getcsv:
        dir: :cacheDir
        maxAge: -1

markup:
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: github
        tabWidth: 4
    goldmark:
        renderer:
            unsafe: true
        extensions:
            typographer:
                enable: true
            linkify: true
            table: true
            strikethrough: true
            taskList: true
    asciidocExt:
        workingFolderCurrent: true
        preserveTOC: true
    blackfriday:
        hrefTargetBlank: true
        noreferrerLinks: true
        nofollowLinks: true